# numpy
* https://numpy.org/numpy-tutorials/
* numpy: NUMerical PYthon 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 같은 자료형
* 순서가 있는 자료형
* 파이썬 list와의 차이는 자료형이 1가지만 들어간다.

## 차원
* 0차원 = 점. 스칼라 (a = 10)
* 1차원 = 선 --------- 백터, 배열, list, tuple, [1,2,3,4]
    * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, Dataframe, matrix
* 3차원 = 입체, 가로, 세로, 높이, 정육면체
* 4차원 = 3차원 요소가 2개 이상
* 5차원 = 4차원 요소가 2개 이상

In [2]:
import numpy as np

* 차원을 출력하는 메서드 .ndim
* 차원의 형태를 출력하는 메서드 .shape

In [13]:
# 0차원 데이터
s = 10
s.ndim    # error
s.shape   # error

AttributeError: 'int' object has no attribute 'shape'

In [2]:
# 1차원 데이터
a = np.array([1,2,3,4,5])
a.ndim     # 1 : 1차원 데이터라는 뜻 (ndarray는 벡터)
a.shape    # (5, ) ; 방향이 없는 벡터

In [11]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c.ndim     # 2
c.shape    # (2,5)

(2, 5)

In [17]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
d.ndim     # 3
d.shape    # (2,2,5) : 2개의 (2행 5열)=2차원이 있다는 의미

(2, 2, 5)

In [19]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]])
e.ndim     # 4
e.shape    # (2, 2, 2, 5) : 2개의 (2개의 2행 5열) = 3차원이 있다는 의미 

(2, 2, 2, 5)

In [22]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]],[[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]]]])
f.ndim     # 5
f.shape    # (2, 2, 2, 2, 5) : 2개의 (2개의 2개의 2행 5열) = 4차원이 있다는 의미

(2, 2, 2, 2, 5)

In [23]:
# 세로로 방향을 가진 행벡터
a2 = np.array([[1],[2],[3],[4],[5]])
a2.shape

(5, 1)

In [27]:
# 가로로 방향을 가진 열벡터
a3 = np.array([1,2,3,4,5])
a3.shape

(5,)

# 넘파이를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [28]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

15


In [29]:
scalar + 10

25

In [30]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]
# 리스트 요소에 10을 곱한 후 다시 리스트로 만드세요.
result = []
for n in b1 :
    result.append(n*10)
print(result)

[10, 20, 30, 40, 50]


In [33]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [35]:
# 2차원 데이터 계산
second = np.array([[1,2,3],[1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [42]:
result = []
for num in second:
    mid_result = []
    for nu in num:
        mid_result.append(num*10)
    result.append(mid_result)
result = np.array(result)
result

array([[[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]]])

In [38]:
# 3차원 데이터의 요소에 10 곱하기
third = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

3

In [44]:
result = []
for num1 in third:
    num1_result = []
    for num2 in num1:
        num2_result = []
        for num3 in num2:
            num2_result.append(num3*10)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)
result

array([[[10, 20, 30],
        [10, 20, 30]],

       [[10, 20, 30],
        [10, 20, 30]]])

In [46]:
# 4차원 데이터 (아래에서 numpy가 효율적인 이유를 볼 수 있음)
fourth = np.array([[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]], [[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]])

In [47]:
result = []
for num1 in fourth:
    num1_result = []
    for num2 in num1:
        num2_result = []
        for num3 in num2:
            num3_result = []
            for num4 in num3:
                num3_result.append(num4*10)
            num2_result.append(num3_result)
        num1_result.append(num2_result)
    result.append(num1_result)
result = np.array(result)
result

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [48]:
fourth*10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [49]:
# 5차원 데이터
fifth = np.array([[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]], [[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]],[[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]], [[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]]])

In [50]:
fifth*10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# numpy에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 보는 것
* .shape: 
* .size:
* .dtype

# ndarray만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [53]:
e3 = np.array((1,2,3.14,'4',5))
print(e3)
e3.dtype

['1' '2' '3.14' '4' '5']


dtype('<U32')

* np.arange(시작, 끝, step)

In [55]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
a2 = np.arange(11,1,-3)
a2

array([11,  8,  5,  2])

In [59]:
a3 = np.arange(1,101,1)

In [60]:
# .reshape(행, 열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)
a4 = a3.reshape(20,5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [62]:
a5 = a3.reshape(5,4,5)
a5

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [66]:
a6 = a3.reshape(4,25)
print(a6)
print(a6.ndim)
print(a6.shape)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]]
2
(4, 25)


In [67]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
a6.flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [72]:
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [73]:
a7.ndim
a7.shape

(3, 2, 2, 2)

In [74]:
a7.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [83]:
a73 = a7.reshape(3,2,2,2)
a73

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [80]:
# np.flip() 행렬의 순서를 뒤집을 때
np.flip(a73)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [82]:
a73[::-1]  # 첫번째 [] 내부 요소만 전환 됨

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

In [84]:
# np.linspace(시작, 끝, 구간 수): 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [85]:
np.linspace(1,10,33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

In [92]:
# 정렬 .sort(), sorted()
f = np.array([5,3,63,1,2,3,66,0])

In [91]:
f.sort()
f

array([ 0,  1,  2,  3,  3,  5, 63, 66])

In [88]:
print(sorted(f, reverse=True))

[np.int64(66), np.int64(63), np.int64(5), np.int64(3), np.int64(3), np.int64(2), np.int64(1), np.int64(0)]


In [9]:
# axis = -1 가장 안쪽 차원 1차원 배열을 정렬 (행 정렬)
# axis = 1 2차원 배열에서 각 열을 정렬 (위아래만 비교)
# axis = 0 다른 2차원 배열과 값 비교
# np.sort() 함수의 axis 기본값은 -1
arr = np.array([[[5,2,8],[1,6,7]],[[4,9,3],[0,2,1]]])
print(arr)
print('-1')
print(np.sort(arr, axis=-1))
print('0')
print(np.sort(arr, axis=0))
print('1')
print(np.sort(arr, axis=1))

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]
-1
[[[2 5 8]
  [1 6 7]]

 [[3 4 9]
  [0 1 2]]]
0
[[[4 2 3]
  [0 2 1]]

 [[5 9 8]
  [1 6 7]]]
1
[[[1 2 7]
  [5 6 8]]

 [[0 2 1]
  [4 9 3]]]


In [94]:
# argsort() 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5,0.5,-7,42,10,0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [95]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [96]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

* np.where(조건, 참, 거짓) 3항 연산

In [10]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.where(num%2==0, '짝수', '홀수')

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

# 배열 합치기

In [13]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a,a.shape)
print(b, b.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)


* np.concatenate((a,b))
* 합치는 기본 방향은 axis=0 행이 늘어남, 아래로 붙음
* axis = 1 열이 늘어남, 옆으로 붙음

In [14]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [19]:
c = np.array([5,6])
print(c,c.ndim,c.shape)

[5 6] 1 (2,)


In [20]:
np.concatenate((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [21]:
d = np.array([[7,8,9]])
print(d, d.ndim, d.shape)

[[7 8 9]] 2 (1, 3)


In [22]:
np.concatenate((a,d), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [23]:
e = np.array([[1,2,3],[4,5,6]])
print(e, e.ndim, e.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [29]:
np.concatenate((e,d), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [30]:
f = np.array([[1,2],[3,4],[5,6]])
print(f, f.ndim, f.shape)

[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)


In [31]:
np.concatenate((e,f), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [33]:
# 전치 행렬: 행과 열을 바꿈
print(f)
print(f.shape)
print(f.T)
print(f.T.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [35]:
np.concatenate((e,f.T), axis=1)    # 이제 붙을 수 있음

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 2, 4, 6]])

In [36]:
np.concatenate((e,f.T))    # 이제 붙을 수 있음

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 5],
       [2, 4, 6]])

# 전치 행렬 만들기
* .T
* .transpose()


In [37]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
e.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
e.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# 브로드 캐스팅
* 벡터와 스칼라, 혹은 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰 주는 것

In [40]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [42]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
print(a,a.ndim, a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 2 (3, 5)


In [43]:
b = np.array([10,20,30,40,50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [44]:
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])